#!/usr/bin/env python3
import click
import pandas as pd
import requests

from bs4 import BeautifulSoup as bs
from terminaltables import SingleTable


def all_conferences():
    URL = 'http://www.engr.uconn.edu/~mukul/cbc.htm'
    soup = bs(requests.get(URL).text, 'lxml')

    calendar = {}
    for section in soup.findAll("center"):
        year = section.find('p').getText().strip()
        table, *_ = pd.read_html(str(section.find('table')), header=0)
        calendar[year] = table
    return calendar


if __name__ == '__main__':
    calendar = all_conferences()

    @click.command(context_settings=dict(help_option_names=['-h', '--help']))
    @click.argument('year', type=click.Choice(calendar.keys()))
    def print_calendar(year):
        frame = calendar[year]
        header = frame.columns.values
        values = frame.values.tolist()
        print(SingleTable([header, *values]).table)

    print_calendar()
